adminUser:
  password: vault:laughingfeet/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: dconde@cloudbees.com
  token: vault:laughingfeet/pipelineUser:token
  username: daveconde
prow:
  hmacToken: vault:laughingfeet/prow:hmacToken
